version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
        - rabbitmq:/var/lib/rabbitmq/
        - rabbitmq:/var/log/rabbitmq/
  authservice-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: authservice-db
    hostname: authservice-db
    environment:
      MYSQL_ROOT_PASSWORD:  mindef123
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    ports:
      - 3306:3306
    volumes:
      - authservice-db-data:/var/lib/mysql
    networks:
      - authservice_network

  phpmyadmin:
    depends_on:
      - authservice-db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: authservice-db
      MYSQL_ROOT_PASSWORD: mindef123 
    networks:
      - authservice_network

volumes:
  authservice-db-data:
  rabbitmq:
networks:
    authservice_network:
    
