apiVersion: v1
kind: Service
metadata:
  labels:
    mindef.service: mindef-frontend
  name: mindef-frontend
  namespace: mindef
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 3000
    targetPort: 3000
  selector:
    mindef.service: mindef-frontend
status:
  loadBalancer: {}