apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authservice-db-data
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  hostPath:
    path: "/mnt/data"
status: {}
