apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mindef-ingress
  namespace: mindef
spec:
  rules:
  - http:
    paths:
    - path: /auth
      pathType: Prefix
      backend:
        service:
          name: mindef-backend
          port: 
            number: 80
