apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mindef-ingress
  namespace: mindef
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - host: mindefdashboard.nl
        path: /
        pathType: Prefix
        backend:
          service:
            name: mindef-frontend
            port: 
              number: 3000
      - host: api.mindefdashboard.nl
        path: /
        pathType: Prefix
        backend:
          service:
            name: mindef-gateway
            port: 
              number: 80

# development only
      - host: authservice.mindefdashboard.nl
        path: /
        pathType: Prefix
        backend:
          service:
            name: authservice
            port: 
              number: 80
