apiVersion: v1
kind: Service
metadata:
  labels:
    mindef.service: authservice
  name: authservice
  namespace: mindef
spec:
  type: ClusterIP
  ports:
  - name: "5002"
    port: 5002
    targetPort: 80
    # nodePort: 30101
  - name: "5003"
    port: 5003
    targetPort: 443
    # nodePort: 30102
  - name: "authservice-db"
    port: 3306
    targetPort: 3306
    # nodePort: 30103
  selector:
    mindef.service: authservice

